Avoid Inkscape 1.0 deprecation warnings
pandoc/lua-filters pull request #227
Opened 2022-05-09 19:10 UTC by postylem

Update the arguments to Inkscape, to be in line with new current Inkscape argument formats (introduced in Inkscape 1.0, released May 2020).

Updating these arguments avoids the following deprecation warnings (which are safe to ignore, but annoying):
```
Warning: Option --without-gui= is deprecated
Warning: Option --file= is deprecated
```
and
```
Warning: Option --export-plain-svg= is deprecated
```
if the format is svg, or
```
Warning: Option --export-png= is deprecated
```
if the format is png.

2022-05-09 19:12 UTC, postylem commented
I just noticed that this has been commented on before in #144, but not implemented in a PR?  This is my first PR here, so I hope I'm being helpful.

2022-05-09 19:39 UTC, alerque approved these changes

2022-05-10 00:16 UTC, postylem commented on diagram-generator/diagram-generator.lua
> +  local inkscape_v_major = inkscape_v_string:match(" ([0-9%.]*) "):gmatch("([0-9]*)%.")()
I added this branch so that now it won't break anything if you are using older inkscape.  This can be removed if that is no longer supported.  But for now it probably should be supported.

2022-05-10 00:20 UTC, postylem commented
OK, I saw that the test CI is running with Ubuntu 20.04 on a docker container which has Inkscape v0.92.5 installed. So this doesn't pass the test on that setup since the new argument format is not accepted by the old Inkscape.  

I pushed a fix which checks the inkscape version and uses the right arguments depending.

2022-05-10 07:35 UTC, alerque requested changes
Good catch, I have v1.0 too but given how slow adoption is making this accessible to v0.9 users makes sense. My suggestion to refactor isn't required if you don't like it, just my suggestion for less code and hence easier to read/understand what is happening.

2022-05-10 07:35 UTC, alerque commented on diagram-generator/diagram-generator.lua
> +  local inkscape_v_major = inkscape_v_string:match(" ([0-9%.]*) "):gmatch("([0-9]*)%.")()
Can this be done with one call to `:gmatch()`?

2022-05-10 11:21 UTC, postylem commented on diagram-generator/diagram-generator.lua
> +  local inkscape_v_major = inkscape_v_string:match(" ([0-9%.]*) "):gmatch("([0-9]*)%.")()
Ah yes, it could.

2022-05-10 11:59 UTC, postylem commented on diagram-generator/diagram-generator.lua
> +  if tonumber(inkscape_v_major) < 1 then
I was going back and forth about something like that earlier.  I think you're right now that I look at it again. A little confusing, but it's better than all the repeated code.

2022-05-10 12:19 UTC, alerque approved these changes
Thanks for the refactor, I think that's quite a bit clearer now.

2022-05-20 07:55 UTC, tarleb commented
Thanks!

We could avoid re-checking the version for every graphic, but the performance impact should be small. It's probably not a big issue.

2022-05-20 07:57 UTC, merged